config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :grandmas do
    resources :transactions, only: [:create]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competence.rb
class Competence < ApplicationRecord
  has_many :grandmas

  def to_s
    name
  end
end

app/models/grandma.rb
class Grandma < ApplicationRecord
  has_many :transactions, dependent: :destroy
  belongs_to :user
  belongs_to :competence

  validates :name, presence: true
  # validates :description, presence: true
  # validates :price, presence: true
  # validates :address, presence: true
  # validates :age, presence: true
  # validates :photo, presence: true
  # validates :competence, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :grandma
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/grandmas_controller.rb
class GrandmasController < ApplicationController
  before_action :set_grandma, only: [:show, :edit, :update, :destroy]
  def show
    @grandma = Grandma.find(params[:id])
  end

  def filtre_loc
    Grandma.near(params[:localisation], 10)
  end

  def filtre_date
    # where not ((t.id IS NOT NULL) AND (t.rentaldate >= '10/10/2019' and t.rentaldate <= '12/12/2019'))
    sql_query = " \
    (transactions.rentaldate >= :start_date \
    AND transactions.rentaldate <= :end_date) \
    AND (transactions.id IS NOT NULL) \
    "
    if params[:localisation].empty?
      if Competence.find(params[:competence_id]).to_s == 'Toutes'
        Grandma.left_outer_joins(:transactions)
               .where.not(sql_query, start_date: params[:start_date], end_date: params[:end_date])
               .distinct
      else
        Grandma.left_outer_joins(:transactions)
               .where.not(sql_query, start_date: params[:start_date], end_date: params[:end_date])
               .where(competence_id: params[:competence_id])
               .distinct
      end
    else
      if Competence.find(params[:competence_id]).to_s == 'Toutes'
        filtre_loc.left_outer_joins(:transactions)
                  .where.not(sql_query, start_date: params[:start_date], end_date: params[:end_date])
                  .distinct
      else
        filtre_loc.left_outer_joins(:transactions)
                  .where.not(sql_query, start_date: params[:start_date], end_date: params[:end_date])
                  .where(competence_id: params[:competence_id])
                  .distinct
      end
    end
  end

  def index
    if params[:start_date].present?
      @grandmas = filtre_date
      @date = [params[:start_date], params[:end_date]]
    else
      if Competence.find(params[:competence_id]).to_s == 'Toutes'
        if params[:localisation].empty?
          @grandmas = Grandma.all
        else
          @grandmas = filtre_loc
        end
      else
        if params[:localisation].empty?
          @grandmas = Grandma.where(competence_id: params[:competence_id])
        else
          @grandmas = filtre_loc.where(competence_id: params[:competence_id])
        end
      end
    end
    @grandmas.geocoded
      @markers = @grandmas.map do |grandma|
        {
          lat: grandma.latitude,
          lng: grandma.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { grandma: grandma }),
          image_url: helpers.asset_url('grandma.svg')
        }
      end
    redirect_to root_path, notice: 'Sorry no grandma found 😔' if @grandmas.empty?
  end

  def new
    @grandma = Grandma.new
    @competences = Competence.where("name <> 'Toutes'")
  end

  def create
    @grandma = Grandma.new(params_grandma)
    @grandma.user = current_user
    if @grandma.save
      redirect_to grandma_path(@grandma)
    else
      render 'new'
    end
  end

  def edit
    @competences = Competence.where("name <> 'Toutes'")
  end

  def update
    if @grandma.update(params_grandma)
      redirect_to @grandma, notice: 'Your Grandma was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @grandma = Grandma.find(params[:id])
    @grandma.destroy
    redirect_to '/', notice: "#{@grandma.name} has been successfully destroyed 🤪"
  end

  private

  def params_grandma
    params.require(:grandma).permit(:name, :description, :price, :address, :age, :competence_id, :photo)
  end

  def set_grandma
    @grandma = Grandma.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @grandma = Grandma.new
    @grandmas = Grandma.all.sample(3)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    @grandma = Grandma.find(params[:grandma_id])
    @transactions = @grandma.transactions.pluck(:rentaldate)
    @transactions.map! do |date|
      date.strftime("%d %m %y")
    end
    if (params[:rentaldate] == '') || (Date.parse(params[:rentaldate]) < Date.current)
      flash.now[:alert] = 'Dates vides ou dans le passée! 🧐'
      render 'grandmas/show'
    else
      @test = @transactions.include?(Date.parse(params[:rentaldate]).strftime("%d %m %y")) unless @transactions.nil?
      if @test
        flash.now[:alert] = 'Date déjà prise pour Mamie sorry'
        render 'grandmas/show'
      else
        @transaction = Transaction.new(params_transaction)
        @transaction.user = current_user
        @transaction.grandma = @grandma
        if @transaction.save
          redirect_to grandma_path(@grandma), notice: "Mamie bien réservée!"
        else
          flash.now[:alert] = @transaction.errors.full_messages.to_s
          render 'grandmas/show'
        end
      end
    end
  end

  def show
    @transaction = Transaction.find(params_transaction)
  end

  private

  def params_transaction
    {
      rentaldate: params[:rentaldate]
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @transaction = @user.transactions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/grandmas/_form.html.erb
<%= simple_form_for(@grandma) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :address %>
  <%= f.input :age %>
  <%= f.association :competence, collection: @competences %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: 'gmp-btn gmp-btn:hover' %>
<% end %>

app/views/grandmas/_grandmacard.html.erb
<div class="center">

  <div class="card">
    <div class="additional">
      <div class="user-card">
        <div class="points center">
           <%= grandma.age %> ans
        </div>
        <svg width="110" height="110" viewBox="0 0 250 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc" class="center">
          <title id="title">Teacher</title>
          <desc id="desc">Cartoon of a Caucasian woman smiling, and wearing black glasses and a purple shirt with white collar drawn by Alvaro Montoro.</desc>
          <style>
            .skin { fill: #eab38f; }
            .eyes { fill: #1f1f1f; }
            .hair { fill: #2f1b0d; }
            .line { fill: none; stroke: #2f1b0d; stroke-width:2px; }
          </style>
          <defs>
            <clipPath id="scene">
              <circle cx="125" cy="125" r="115"/>
            </clipPath>
            <clipPath id="lips">
              <path d="M 106,132 C 113,127 125,128 125,132 125,128 137,127 144,132 141,142  134,146  125,146  116,146 109,142 106,132 Z" />
            </clipPath>
          </defs>
          <circle cx="125" cy="125" r="120" fill="rgba(0,0,0,0.15)" />
          <g stroke="none" stroke-width="0" clip-path="url(#scene)">
            <rect x="0" y="0" width="250" height="250" fill="#b0d2e5" />
            <g id="head">
              <path fill="none" stroke="#111111" stroke-width="2" d="M 68,103 83,103.5" />
              <path class="hair" d="M 67,90 67,169 78,164 89,169 100,164 112,169 125,164 138,169 150,164 161,169 172,164 183,169 183,90 Z" />
              <circle cx="125" cy="100" r="55" class="skin" />
              <ellipse cx="102" cy="107" rx="5" ry="5" class="eyes" id="eye-left" />
              <ellipse cx="148" cy="107" rx="5" ry="5" class="eyes" id="eye-right" />
              <rect x="119" y="140" width="12" height="40" class="skin" />
              <path class="line eyebrow" d="M 90,98 C 93,90 103,89 110,94" id="eyebrow-left" />
              <path class="line eyebrow" d="M 160,98 C 157,90 147,89 140,94" id="eyebrow-right"/>
              <path stroke="#111111" stroke-width="4" d="M 68,103 83,102.5" />
              <path stroke="#111111" stroke-width="4" d="M 182,103 167,102.5" />
              <path stroke="#050505" stroke-width="3" fill="none" d="M 119,102 C 123,99 127,99 131,102" />
              <path fill="#050505" d="M 92,97 C 85,97 79,98 80,101 81,104 84,104 85,102" />
              <path fill="#050505" d="M 158,97 C 165,97 171,98 170,101 169,104 166,104 165,102" />
              <path stroke="#050505" stroke-width="3" fill="rgba(240,240,255,0.4)" d="M 119,102 C 118,111 115,119 98,117 85,115 84,108 84,104 84,97 94,96 105,97 112,98 117,98 119,102 Z" />
              <path stroke="#050505" stroke-width="3" fill="rgba(240,240,255,0.4)" d="M 131,102 C 132,111 135,119 152,117 165,115 166,108 166,104 166,97 156,96 145,97 138,98 133,98 131,102 Z" />
              <path class="hair" d="M 60,109 C 59,39 118,40 129,40 139,40 187,43 189,99 135,98 115,67 115,67 115,67 108,90 80,109 86,101 91,92 92,87 85,99 65,108 60,109" />
              <path id="mouth" fill="#d73e3e" d="M 106,132 C 113,127 125,128 125,132 125,128 137,127 144,132 141,142  134,146  125,146  116,146 109,142 106,132 Z" />
              <path id="smile" fill="white" d="M125,141 C 140,141 143,132 143,132 143,132 125,133 125,133 125,133 106.5,132 106.5,132 106.5,132 110,141 125,141 Z" clip-path="url(#lips)" />
            </g>
            <g id="shirt">
              <path fill="#8665c2" d="M 132,170 C 146,170 154,200 154,200 154,200 158,250 158,250 158,250 92,250 92,250 92,250 96,200 96,200 96,200 104,170 118,170 118,170 125,172 125,172 125,172 132,170 132,170 Z"/>
              <path id="arm-left" class="arm" stroke="#8665c2" fill="none" stroke-width="14" d="M 118,178 C 94,179 66,220 65,254" />
              <path id="arm-right" class="arm" stroke="#8665c2" fill="none" stroke-width="14" d="M 132,178 C 156,179 184,220 185,254" />
              <path fill="white" d="M 117,166 C 117,166 125,172 125,172 125,182 115,182 109,170 Z" />
              <path fill="white" d="M 133,166 C 133,166 125,172 125,172 125,182 135,182 141,170 Z" />
              <circle cx="125" cy="188" r="4" fill="#5a487b" />
              <circle cx="125" cy="202" r="4" fill="#5a487b" />
              <circle cx="125" cy="216" r="4" fill="#5a487b" />
              <circle cx="125" cy="230" r="4" fill="#5a487b" />
              <circle cx="125" cy="244" r="4" fill="#5a487b" />
              <path stroke="#daa37f" stroke-width="1" class="skin hand" id="hand-left" d="M 51,270 C 46,263 60,243 63,246 65,247 66,248 61,255 72,243 76,238 79,240 82,243 72,254 69,257 72,254 82,241 86,244 89,247 75,261 73,263 77,258 84,251 86,253 89,256 70,287 59,278" />
              <path stroke="#daa37f" stroke-width="1" class="skin hand" id="hand-right" d="M 199,270 C 204,263 190,243 187,246 185,247 184,248 189,255 178,243 174,238 171,240 168,243 178,254 181,257 178,254 168,241 164,244 161,247 175,261 177,263 173,258 166,251 164,253 161,256 180,287 191,278"/>
            </g>
          </g>
        </svg>
      </div>
      <div class="more-info">
        <h1><%= grandma.name %></h1>
        <div class="coords">
        </div>
        <div class="stats">

          <div>
            <i class="fa fa-group"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="general">
      <h1><%= grandma.name %></h1>
        <p>Competence : <%= grandma.competence.to_s %></p>
        <p>Price :  <%= grandma.price %>0 € /jours</p>
    </div>
  </div>

app/views/grandmas/_info_window.html.erb
<p>grandmaaa pooooower</p>
<p><%= grandma.name %></p>

app/views/grandmas/edit.html.erb
<%= render '/pages/navbar' %>

<div class="container">
  <h1>My Grandma ! 👵</h1>

  <h2>My grandma's informations</h2>

  <%= render 'form', grandma: @grandma %>
</div>

app/views/grandmas/index.html.erb
<%= render "pages/navbar" %>
<h1 style="text-align: center; margin-bottom: 30px; margin-top: 30px;">Nos mémés n'attendent que vous !</h1>




<div class="container-fluid">
<div class="col-12 col-lg-8">
  <div class="formdate">
    <%= form_with url: grandmas_path, method: :get, local: true, class: 'formcenter' do |form| %>
    <%= form.text_field :localisation, value: params[:localisation], type: :hidden %>
    <%= form.text_field :competence_id, value: params[:competence_id], type: :hidden %>
    <%= form.date_field :start_date, value: (@date[0] unless @date.nil?)  %>
    <%= form.date_field :end_date, class: 'ml-1', value: (@date[1] unless @date.nil?)%>
    <%= form.submit :search, value: "Rechercher", class: 'btn gmp-btn m-0 ml-2' %>
    <% end %>
      <%= form_with url: grandmas_path, method: :get, local: true do |form| %>
    <%= form.text_field :localisation, value: params[:localisation], type: :hidden %>
    <%= form.text_field :competence_id, value: params[:competence_id], type: :hidden %>
    <%= form.submit :Reset, class: 'btn gmp-btn m-0 ml-2' %>
    <% end %>
  </div>
</div>
<div class="col-12 col-lg-4"></div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="cards">
        <% @grandmas.each do |grandma|%>
          <div class="card">
            <div class="additional">
              <div class="user-card">
                <div class="points center">
                 <%= grandma.age %> ans
                </div>
                <div class="card-product">
                <%= link_to '', grandma_path(grandma)  %>
                <%= image_tag grandma.photo.url(:thumnail), class: 'avatar' %>
                </div>
              </div>
              <div class="more-info">
                <h1><%= grandma.name %></h1>
                <div class="coords">
                </div>
                <div class="stats">
                  <div>
                    <i class="fa fa-group"></i>
                  </div>
                </div>
              </div>
            </div>
            <div class="general">
              <h1><%= grandma.name %></h1>
              <p>Competence : <%= grandma.competence.to_s %></p>
              <p>Price :  <%= grandma.price %>0 € /jours</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div class="map-container">
        <div
        id="map"
        style="width: 100%;
        height: 100vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>
  </div>
</div>

app/views/grandmas/new.html.erb
<%= render '/pages/navbar' %>

<div class="container">
  <h1>New grandma ! 👵</h1>

  <h2>My grandma's informations</h2>

  <%= render 'form', grandma: @grandma %>
</div>

app/views/grandmas/show.html.erb
<div class="d-flex flex-column mheight100">
<%= render '/pages/navbar' %>
  <div class="height100">
<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
<% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>
  <div class="container">
<div class="grid">
  <%= render '/pages/showcard' %>
<div class="reservation-infos">
  <div class="book-date">
    <%= form_with url: grandma_transactions_path(@grandma), method: :post, local: true do |form| %>
    <%= form.date_field :rentaldate %>

    <p><%= form.submit :mamieresa, value: "Réserver", class: "btn gmp-btn gmp-btn:hover" %></p>
  <% end %>
  </div>
  <div class="planning">
    <!-- <ul class="list-group md-3 ml-3 w-50"> -->
      <ul class="list-group">
        <% nbtransac = @grandma.transactions.select{|transac| transac.rentaldate >= Date.current }.size %>
      <% if nbtransac != 0 %>
      <li class="list-group-item list-group-item-dark">Yeee mémé est bookée sur <%= pluralize(nbtransac,'date', plural: 'dates') %> :</li>
      <% end %>
      <% @grandma.transactions.each do |transac| %>
      <% if transac.rentaldate >= Date.current %>
        <li class="list-group-item list-group-item-secondary"><%= transac.rentaldate.strftime("%d %B %Y") %></li>
      <% end %>
      <% end %>
    </ul>
  </div>
  </div>
</div>

<!--<div class="hoover; container49">-->
  <% if user_signed_in? %>
  <% if current_user.id == @grandma.user_id %>
    <p><%= link_to "Modifier ma mémé", edit_grandma_path(@grandma), class: "btn gmp-btn gmp-btn:hover" %></p>
    <p><%= link_to 'Supprimer', grandma_path(@grandma), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
  <% end %>
<!--</div>-->
</div>


  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Grandma power!!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style='min-height:100vh'>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <%= render '/pages/footer' %>

  </body>
</html>

app/views/pages/_cardsGrandma.html.erb
<div class="grid-home">
  <% @grandmas.each do |grandma|%>
    <div class="card-product">
 <%= link_to '', grandma_path(grandma)  %>
      <%= image_tag grandma.photo.url(:thumnail), class: 'avatar' %>
      <div class="card-product-infos">
        <h2><%=grandma.name%></h2>
        <p><%=grandma.competence.to_s%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_footer.html.erb
  <div class="w3hubs-footer heightsmall">
        <div class="w3hubs-icon">
          <ul>
              <a href="#" class="color5"><i class="fab fa-instagram" width="100"></i></a>
              <a href="#" class="color5"><i class="fab fa-facebook"></i></a>
              <a href="#" class="color5"><i class="fab fa-twitter"></i></a>
              <a href="#" class="color5"><i class="fab fa-linkedin"></i></a>
          </ul>
        </div>
        <div class="w3hubs-nav">
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Gallery</a></li>
            <li class="p1"><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="w3hubs-nav1">
          <ul>
            <li><a href="#">Product</a></li>
            <li><a href="#">new</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Media</a></li>
          </ul>
        </div>
     </div>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon heightsmall">
  <%= link_to image_tag('logo_book_meme.png', class: 'logo'), root_path %>
     <!-- <img <%#=  image_tag('grandmalogo1.png')%> -->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if !user_signed_in?  %>
        <div id="links">
        <%= link_to 'Connexion', new_user_session_path, class: 'nav-link' %>
        <%= link_to 'Inscription', new_user_registration_path, class: 'nav-link' %>
        <!-- <a class="nav-link" href="#">Login</a> -->
        </div>
        <% end %>

      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Create account</a>
      </li> -->
      <% if user_signed_in?  %>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"><%= link_to 'Ajouter une mémé', new_grandma_path, class: 'dropdown-item' %></a>
          <a class="dropdown-item" href="#"><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></a>
          <a class="dropdown-item" href="#"><%= link_to 'Compte', user_path(current_user.id), method: :get, class: 'dropdown-item' %></a>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/_searchgdma.html.erb
<!-- fonction pour desactiver ajax (remote false) -->
<div class="searchhome">
  <div>
    <%= form_with url: grandmas_path, method: :get, local: true do |form| %>
    <%= form.label :localisation, class: "labels" %>
    <%= form.text_field :localisation, id: 'flat_address' %>
  </div>
  <div class="competence">
    <%= form.label :competence, class: "labels block" %>
    <%= form.select(:competence_id, options_from_collection_for_select(Competence.all, :id, :name), class: "block") %>
  </div>
  <div>
      <%= form.submit :search, value: "Rechercher", class: "btn gmp-btn gmp-btn:hover" %>
  </div>
    <% end %>
</div>

app/views/pages/_showcard.html.erb
<div id="container52">
  <div class="product-details">
    <h1 id="title12"><%= @grandma.name %></h1>
    <p class="information"><%= @grandma.description %></p>
  <div class="control23">
  </div>
  </div>

  <div class="product-image">
    <img> <%= cl_image_tag @grandma.photo, height: 300, width: 400, crop: :fill %>
      <div class="info">
        <h2>Informations</h2>
        <ul>
          <li><strong>Age : </strong><%= @grandma.age %> ans</li>
          <li><strong>Compétence : </strong><%= @grandma.competence.to_s %></li>
          <li><strong>Adresse : </strong><%= @grandma.address %></li>
          <li><strong>Prix : </strong><%= @grandma.price %>0 € /jour</li>
        </ul>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="d-flex flex-column mheight100">

<%= render 'navbar' %>

<div class="height100">
  <div class="banner">
    <h1>Book ta mémé</h1>
    <p>Prêt à profiter du pouvoir d'une vieille et sage grand-mère ?</p>
    <%= render 'searchgdma' %>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
  <div class="container">
    <h2>Découvrez ces supers mémés !</h2>
    <%= render 'cardsGrandma' %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<%= render '/pages/navbar' %>

<div class="main-container">

  <div class="sidebar">
    <h1>Mon profil</h1>
    <div><img class="avatar avatar-large" src="https://kitt.lewagon.com/placeholder/users/ssaunier" alt=""></div>
    <div>
      <div class="profilcontainer">
      <p><%= @user.first_name %></p>
      </div>
      <div class="profilcontainer">
      <p><%= @user.last_name %></p>
      </div>
      <div class="profilcontainer">
      <p><%= @user.email %></p>
      </div>
      <div class="modifier">
      <a href="" class="gmp-btn">Modifier</a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="reservationdiv">
      <h1>Mes réservations</h1>
    </div>
    <div class="row">
      <div class="cards col-6">
        <% @transaction.each do |transaction|%>
        <div class="card">
          <div class="additional">
            <div class="user-card">
              <div class="points center">
               <%= transaction.grandma.age %> ans
             </div>
             <div class="card-product">
              <%= link_to '', grandma_path(transaction.grandma_id)  %>
              <%= image_tag transaction.grandma.photo.url(:thumnail), class: 'avatar' %>
            </div>
          </div>
          <div class="more-info">
            <h1><%= transaction.grandma.name %></h1>
            <h2 style="color: white">Votre réservation est prévue le :<%= transaction.rentaldate %></h2>
            <div class="stats">
              <div>
                <i class="fa fa-group"></i>
              </div>
            </div>
          </div>
        </div>
        <div class="general">
          <h1><%= transaction.grandma.name %></h1>
          <p>Competence : <%= transaction.grandma.competence.to_s %></p>
          <p>Price :  <%= transaction.grandma.price %>0 € /jours</p>
        </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>